-- register /bodyguard to call a function (we can just put the function straight inside the SetCommand function as an argument)
SetCommand("bodyguard",function(name)
	local model = get_model(name)
	if model then -- if get_model returned a model then spawn a ped
		local x,y,z = PedGetOffsetInWorldCoords(gPlayer,0,1,0) -- 1 m in front of the player
		local ped = PedCreateXYZ(model,x,y,z)
		PedFaceHeading(ped,math.deg(PedGetHeading(gPlayer)),0) -- PedGetHeading returns radians, but PedFaceHeading takes degrees
		recruit_ped(ped)
	elseif name then
		PrintError("unknown ped model: "..name) -- if there wasn't a valid model for this name, print this
	else
		PrintError("expected ped name") -- but if there wasn't even a name given, print this
	end
end)

-- get a ped model given a name (where name can be the model number, model name, or short name of a ped)
get_model = function(name)
	local model = tonumber(name)
	if model then
		model = math.floor(model) -- since the string "name" could be converted to a number, let's floor it (drop any decimal point)
		if model >= 2 and model <= 258 then
			return model -- only return the model if it is a valid ped model id
		end
	end
	name = string.lower(name) -- make "name" lowercase so we can compare it against other lowercase strings (and be case insensitive)
	for _,v in ipairs(gNames) do
		if name == string.lower(v[2]) or name == string.lower(v[3]) then
			return v[1] -- return the model id if the "name" is equal to the model or name of the ped
		end
	end
	-- nothing is returned if "name" couldn't be converted to a valid model
end

-- a ped can only recruit one other ped. so if we want to allow multiple bodyguards, we have to recruit them in a "chain"
recruit_ped = function(ped)
	local leader = gPlayer -- let's start with the player (since that is who we want to recruit the ped)
	while PedHasAllyFollower(leader) do
		leader = PedGetAllyFollower(leader) -- but keep getting the next ped in the recruit chain until we get to the end
	end
	PedRecruitAlly(leader,ped) -- now we can recruit the ped since we found the end of the chain
end

-- list of names that can be used for peds
gNames = {
	-- {id, model, name}
	{2,"DOgirl_Zoe_EG","Zoe"},
	{3,"NDGirl_Beatrice","Beatrice"},
	{4,"NDH1a_Algernon","Algernon"},
	{5,"NDH1_Fatty","Fatty"},
	{6,"ND2nd_Melvin","Melvin"},
	{7,"NDH2_Thad","Thad"},
	{8,"NDH3_Bucky","Bucky"},
	{9,"NDH2a_Cornelius","Cornelius"},
	{10,"NDLead_Earnest","Earnest"},
	{11,"NDH3a_Donald","Donald"},
	{12,"JKH1_Damon","Damon"},
	{13,"JKH1a_Kirby","Kirby"},
	{14,"JKGirl_Mandy","Mandy"},
	{15,"JKH2_Dan","Dan"},
	{16,"JKH2a_Luis","Luis"},
	{17,"JKH3_Casey","Casey"},
	{18,"JKH3a_Bo","Bo"},
	{19,"JKlead_Ted","Ted"},
	{20,"JK2nd_Juri","Juri"},
	{21,"GR2nd_Peanut","Peanut"},
	{22,"GRH2A_Hal","Hal"},
	{23,"GRlead_Johnny","Johnny"},
	{24,"GRH1_Lefty","Lefty"},
	{25,"GRGirl_Lola","Lola"},
	{26,"GRH3_Lucky","Lucky"},
	{27,"GRH1a_Vance","Vance"},
	{28,"GRH3a_Ricky","Ricky"},
	{29,"GRH2_Norton","Norton"},
	{30,"PRH1_Gord","Gord"},
	{31,"PRH1a_Tad","Tad"},
	{32,"PRH2a_Chad","Chad"},
	{33,"PR2nd_Bif","Bif"},
	{34,"PRH3_Justin","Justin"},
	{35,"PRH2_Bryce","Bryce"},
	{36,"PRH2_Bryce_OBOX","Bryce"},
	{37,"PRlead_Darby","Darby"},
	{38,"PRGirl_Pinky","Pinky"},
	{39,"GN_Asiangirl","Angie"},
	{40,"PRH3a_Parker","Parker"},
	{41,"DOH2_Jerry","Jerry"},
	{42,"DOH1a_Otto","Otto"},
	{43,"DOH2a_Leon","Leon"},
	{44,"DOH1_Duncan","Duncan"},
	{45,"DOH3_Henry","Henry"},
	{46,"DOH3a_Gurney","Gurney"},
	{47,"DO2nd_Omar","Omar"},
	{48,"DOGirl_Zoe","Zoe"},
	{49,"PF2nd_Max","Max"},
	{50,"PFH1_Seth","Seth"},
	{51,"PFH2_Edward","Edward"},
	{52,"PFlead_Karl","Karl"},
	{53,"TO_Orderly","Theo"},
	{54,"TE_HallMonitor","MissPeabody"},
	{55,"TE_GymTeacher","MrBurton"},
	{56,"TE_Janitor","MrLuntz"},
	{57,"TE_English","MrGalloway"},
	{58,"TE_Cafeteria","Edna"},
	{59,"TE_Secretary","MissWinston"},
	{60,"TE_Nurse","MrsMcRae"},
	{61,"TE_MathTeacher","MrHuntingdon"},
	{62,"TE_Librarian","MrsCarvin"},
	{63,"TE_Art","MsPhillips"},
	{64,"TE_Biology","MrSlawter"},
	{65,"TE_Principal","DrCrabblesnitch"},
	{66,"GN_Littleblkboy","Sheldon"},
	{67,"GN_SexyGirl","Christy"},
	{68,"GN_Littleblkgirl","Gloria"},
	{69,"GN_Hispanicboy","Pedro"},
	{70,"GN_Greekboy","Constantinos"},
	{71,"GN_Fatboy","Ray"},
	{72,"GN_Boy01","Ivan"},
	{73,"GN_Boy02","Trevor"},
	{74,"GN_Fatgirl","Eunice"},
	{75,"DOlead_Russell","Russell"},
	{76,"TO_Business1","DrBambillo"},
	{77,"TO_Business2","MrSullivan"},
	{78,"TO_BusinessW1","MsKopke"},
	{79,"TO_BusinessW2","MsRushinski"},
	{80,"TO_RichW1","MsIsaacs"},
	{81,"TO_RichW2","BethanyJones"},
	{82,"TO_Fireman","ORourke"},
	{83,"TO_Cop","OfficerMonson"},
	{84,"TO_Comic","ZackOwens"},
	{85,"GN_Bully03","Trent"},
	{86,"TO_Bikeowner","TobiasMason"},
	{87,"TO_Hobo","MrGrant"},
	{88,"Player_Mascot","Mascot"},
	{89,"TO_GroceryOwner","MrOh"},
	{90,"GN_Sexygirl_UW","Christy"},
	{91,"DOLead_Edgar","Edgar"},
	{92,"JK_LuisWrestle","Luis"},
	{93,"JKGirl_MandyUW","Mandy"},
	{94,"PRGirl_PinkyUW","Pinky"},
	{95,"NDGirl_BeatriceUW","Beatrice"},
	{96,"GRGirl_LolaUW","Lola"},
	{97,"TO_Cop2","OfficerWilliams"},
	{98,"Player_OWres","Jimmy"},
	{99,"GN_Bully02","Davis"},
	{100,"TO_RichM1","MrBreckindale"},
	{101,"TO_RichM2","MrDoolin"},
	{102,"GN_Bully01","Troy"},
	{103,"TO_FireOwner","Nate"},
	{104,"TO_CSOwner_2","MrCarmichael"},
	{105,"TO_CSOwner_3","NickyCharles"},
	{106,"TE_Chemistry","MrWatts"},
	{107,"TO_Poorwoman","MissAbby"},
	{108,"TO_MotelOwner","Mihailovich"},
	{109,"JKKirby_FB","Kirby"},
	{110,"JKTed_FB","Ted"},
	{111,"JKDan_FB","Dan"},
	{112,"JKDamon_FB","Damon"},
	{113,"TO_Carny02","Freeley"},
	{114,"TO_Carny01","Dorsey"},
	{115,"TO_CarnyMidget","Hector"},
	{116,"TO_Poorman2","Osbourne"},
	{117,"PRH2A_Chad_OBOX","Chad"},
	{118,"PRH3_Justin_OBOX","Justin"},
	{119,"PRH3a_Parker_OBOX","Parker"},
	{120,"TO_BarberRich","MariaTheresa"},
	{121,"GenericWrestler","Bob"},
	{122,"ND_FattyWrestle","Fatty"},
	{123,"TO_Industrial","Chuck"},
	{124,"TO_Associate","Ian"},
	{125,"TO_Asylumpatient","Fenwick"},
	{126,"TE_Autoshop","Neil"},
	{127,"TO_Mailman","MrSvenson"},
	{128,"TO_Tattooist","Denny"},
	{129,"TE_Assylum","MrGalloway"},
	{130,"Nemesis_Gary","Gary"},
	{131,"TO_Oldman2","Krakauer"},
	{132,"TO_BarberPoor","MrMoratti"},
	{133,"PR2nd_Bif_OBOX","Bif"},
	{134,"Peter","Peter"},
	{135,"TO_RichM3","MrSmith"},
	{136,"Rat_Ped","Rat"},
	{137,"GN_LittleGirl_2","Melody"},
	{138,"GN_LittleGirl_3","Karen"},
	{139,"GN_WhiteBoy","Gordon"},
	{140,"TO_FMidget","Brandy"},
	{141,"Dog_Pitbull","Pitbull"},
	{142,"GN_SkinnyBboy","Lance"},
	{143,"TO_Carnie_female","Crystal"},
	{144,"TO_Business3","MrMartin"},
	{145,"GN_Bully04","Ethan"},
	{146,"GN_Bully05","Wade"},
	{147,"GN_Bully06","Tom"},
	{148,"TO_Business4","MrRamirez"},
	{149,"TO_Business5","MrHuntingdon"},
	{150,"DO_Otto_asylum","Otto"},
	{151,"TE_History","MrWiggins"},
	{152,"TO_Record","Floyd"},
	{153,"DO_Leon_Assylum","Leon"},
	{154,"DO_Henry_Assylum","Henry"},
	{155,"NDH1_FattyChocolate","Fatty"},
	{156,"TO_GroceryClerk","Stan"},
	{157,"TO_Handy","Handy"},
	{158,"TO_Orderly2","Gregory"},
	{159,"GN_Hboy_Ween","Pedro"},
	{160,"Nemesis_Ween","Gary"},
	{161,"GRH3_Lucky_Ween","Lucky"},
	{162,"NDH3a_Donald_ween","Donald"},
	{163,"PRH3a_Parker_Ween","Parker"},
	{164,"JKH3_Casey_Ween","Casey"},
	{165,"Peter_Ween","Peter"},
	{166,"GN_AsianGirl_Ween","Angie"},
	{167,"PRGirl_Pinky_Ween","Pinky"},
	{168,"JKH1_Damon_ween","Damon"},
	{169,"GN_WhiteBoy_Ween","Gordon"},
	{170,"GN_Bully01_Ween","Ivan"},
	{171,"GN_Boy02_Ween","Trevor"},
	{172,"PR2nd_Bif_OBOX_D1","Bif"},
	{173,"GRH1a_Vance_Ween","Vance"},
	{174,"NDH2_Thad_Ween","Thad"},
	{175,"PRGirl_Pinky_BW","Pinky"},
	{176,"DOlead_Russell_BU","Russell"},
	{177,"PRH1a_Tad_BW","Tad"},
	{178,"PRH2_Bryce_BW","Bryce"},
	{179,"PRH3_Justin_BW","Justin"},
	{180,"GN_Asiangirl_CH","Angie"},
	{181,"GN_Sexygirl_CH","Christy"},
	{182,"PRGirl_Pinky_CH","Pinky"},
	{183,"TO_NH_Res_01","MrBuba"},
	{184,"TO_NH_Res_02","MrGordon"},
	{185,"TO_NH_Res_03","MrsLisburn"},
	{186,"NDH1_Fatty_DM","Fatty"},
	{187,"TO_PunkBarber","Betty"},
	{188,"FightingMidget_01","Lightning"},
	{189,"FightingMidget_02","Zeke"},
	{190,"TO_Skeletonman","Alfred"},
	{191,"TO_Beardedwoman","Paris"},
	{192,"TO_CarnieMermaid","Courtney"},
	{193,"TO_Siamesetwin2","Delilah"},
	{194,"TO_Paintedman","Drew"},
	{195,"TO_GN_Workman","Castillo"},
	{196,"DOLead_Edgar_GS","Edgar"},
	{197,"DOH3a_Gurney_GS","Gurney"},
	{198,"DOH2_Jerry_GS","Jerry"},
	{199,"DOH2a_Leon_GS","Leon"},
	{200,"GRH2a_Hal_GS","Hal"},
	{201,"GRH2_Norton_GS","Norton"},
	{202,"GR2nd_Peanut_GS","Peanut"},
	{203,"GRH1a_Vance_GS","Vance"},
	{204,"JKH3a_Bo_GS","Bo"},
	{205,"JKH1_Damon_GS","Damon"},
	{206,"JK2nd_Juri_GS","Juri"},
	{207,"JKH1a_Kirby_GS","Kirby"},
	{208,"NDH1a_Algernon_GS","Algernon"},
	{209,"NDH3_Bucky_GS","Bucky"},
	{210,"NDH2_Thad_GS","Thad"},
	{211,"PRH3a_Parker_GS","Parker"},
	{212,"PRH3_Justin_GS","Justin"},
	{213,"PRH1a_Tad_GS","Tad"},
	{214,"PRH1_Gord_GS","Gord"},
	{215,"NDLead_Earnest_EG","Earnest"},
	{216,"JKlead_Ted_EG","Ted"},
	{217,"GRlead_Johnny_EG","Johnny"},
	{218,"PRlead_Darby_EG","Darby"},
	{219,"Dog_Pitbull2","Pitbull"},
	{220,"Dog_Pitbull3","Pitbull"},
	{221,"TE_CafeMU_W","Edna"},
	{222,"TO_Millworker","McInnis"},
	{223,"TO_Dockworker","Johnson"},
	{224,"NDH2_Thad_PJ","Thad"},
	{225,"GN_Lblkboy_PJ","Sheldon"},
	{226,"GN_Hboy_PJ","Pedro"},
	{227,"GN_Boy01_PJ","Ivan"},
	{228,"GN_Boy02_PJ","Trevor"},
	{229,"TE_Gym_Incog","MrBurton"},
	{230,"JK_Mandy_Towel","Mandy"},
	{231,"JK_Bo_FB","Bo"},
	{232,"JK_Casey_FB","Casey"},
	{233,"PunchBag","PunchBag"},
	{234,"TO_Cop3","OfficerMonson"},
	{235,"GN_GreekboyUW","Constantinos"},
	{236,"TO_Construct01","McInnis"},
	{237,"TO_Construct02","McInnis"},
	{238,"TO_Cop4","OfficerWilliams"},
	{239,"PRH2_Bryce_OBOX_D1","Bryce"},
	{240,"PRH2_Bryce_OBOX_D2","Bryce"},
	{241,"PRH2A_Chad_OBOX_D1","Chad"},
	{242,"PRH2A_Chad_OBOX_D2","Chad"},
	{243,"PR2nd_Bif_OBOX_D2","Bif"},
	{244,"PRH3_Justin_OBOX_D1","Justin"},
	{245,"PRH3_Justin_OBOX_D2","Justin"},
	{246,"PRH3a_Prkr_OBOX_D1","Parker"},
	{247,"PRH3a_Prkr_OBOX_D2","Parker"},
	{248,"TE_Geography","TEMP"},
	{249,"TE_Music","TEMP"},
	{250,"TO_ElfF","TEMP"},
	{251,"TO_ElfM","TEMP"},
	{252,"TO_HoboSanta","TEMP"},
	{253,"TO_Santa","TEMP"},
	{254,"TO_Santa_NB","TEMP"},
	{255,"Peter_Nutcrack","Peter"},
	{256,"GN_Fatgirl_Fairy","Eunice"},
	{257,"GN_Lgirl_2_Flower","Melody"},
	{258,"GN_Hboy_Flower","Pedro"},
}
