; Listing generated by Microsoft (R) Optimizing Compiler Version 19.23.28107.0 

	TITLE	C:\Program Files (x86)\Steam\steamapps\common\Bully Scholarship Edition\_derpy_script_loader\src\client\library\lib_hook.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_dslopen_hook
PUBLIC	??_C@_08IEONNEJB@dsl_hook@			; `string'
PUBLIC	??_C@_0BL@DGPOAGDD@failed?5to?5replace?5function@ ; `string'
PUBLIC	??_C@_04HDOCAJNK@?$CFs?$CFs@			; `string'
PUBLIC	??_C@_0BK@FGOEOOHP@an?5unknown?5error?5occurred@ ; `string'
PUBLIC	??_C@_0BI@PGPBJMFK@failed?5to?5prepare?5hooks@	; `string'
PUBLIC	??_C@_01EFFIKLCJ@n@				; `string'
PUBLIC	??_C@_0BE@GADLECGJ@failed?5to?5run?5hooks@	; `string'
PUBLIC	??_C@_0BG@KLOCBMAN@incompatible?5function@	; `string'
PUBLIC	??_C@_0BD@FMPBNBIP@hook?5limit?5reached@	; `string'
PUBLIC	??_C@_0O@CANMLFDD@function?5hook@		; `string'
PUBLIC	??_C@_0BI@BGFKABCN@corrupted?5function?5hook@	; `string'
PUBLIC	??_C@_0BG@HOEJKLNH@invalid?5function?5hook@	; `string'
PUBLIC	??_C@_04BDLIKKMN@__gc@				; `string'
PUBLIC	??_C@_0BE@IDIDLGJD@GetBaseGameFunction@		; `string'
PUBLIC	??_C@_0N@EJLAAODM@HookFunction@			; `string'
PUBLIC	??_C@_0BD@IMEMLEFD@RemoveFunctionHook@		; `string'
PUBLIC	??_C@_0BA@PAHFPGMI@ReplaceFunction@		; `string'
EXTRN	_free:PROC
EXTRN	_malloc:PROC
EXTRN	_realloc:PROC
EXTRN	_lua_gettop:PROC
EXTRN	_lua_settop:PROC
EXTRN	_lua_pushvalue:PROC
EXTRN	_lua_insert:PROC
EXTRN	_lua_checkstack:PROC
EXTRN	_lua_isstring:PROC
EXTRN	_lua_type:PROC
EXTRN	_lua_toboolean:PROC
EXTRN	_lua_tostring:PROC
EXTRN	_lua_touserdata:PROC
EXTRN	_lua_pushnil:PROC
EXTRN	_lua_pushnumber:PROC
EXTRN	_lua_pushstring:PROC
EXTRN	_lua_pushcclosure:PROC
EXTRN	_lua_pushboolean:PROC
EXTRN	_lua_pushlightuserdata:PROC
EXTRN	_lua_rawget:PROC
EXTRN	_lua_rawgeti:PROC
EXTRN	_lua_newtable:PROC
EXTRN	_lua_newuserdata:PROC
EXTRN	_lua_settable:PROC
EXTRN	_lua_rawset:PROC
EXTRN	_lua_rawseti:PROC
EXTRN	_lua_setmetatable:PROC
EXTRN	_lua_pcall:PROC
EXTRN	_luaL_typerror:PROC
EXTRN	_luaL_argerror:PROC
EXTRN	_luaL_checktype:PROC
EXTRN	_luaL_error:PROC
EXTRN	_luaL_ref:PROC
EXTRN	_luaL_unref:PROC
EXTRN	_getDslState:PROC
EXTRN	_getDslPrintPrefix:PROC
EXTRN	_addScriptEventCallback:PROC
EXTRN	_printConsoleFormatted:PROC
EXTRN	__fltused:DWORD
;	COMDAT ??_C@_0BA@PAHFPGMI@ReplaceFunction@
CONST	SEGMENT
??_C@_0BA@PAHFPGMI@ReplaceFunction@ DB 'ReplaceFunction', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BD@IMEMLEFD@RemoveFunctionHook@
CONST	SEGMENT
??_C@_0BD@IMEMLEFD@RemoveFunctionHook@ DB 'RemoveFunctionHook', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0N@EJLAAODM@HookFunction@
CONST	SEGMENT
??_C@_0N@EJLAAODM@HookFunction@ DB 'HookFunction', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0BE@IDIDLGJD@GetBaseGameFunction@
CONST	SEGMENT
??_C@_0BE@IDIDLGJD@GetBaseGameFunction@ DB 'GetBaseGameFunction', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_04BDLIKKMN@__gc@
CONST	SEGMENT
??_C@_04BDLIKKMN@__gc@ DB '__gc', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0BG@HOEJKLNH@invalid?5function?5hook@
CONST	SEGMENT
??_C@_0BG@HOEJKLNH@invalid?5function?5hook@ DB 'invalid function hook', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BI@BGFKABCN@corrupted?5function?5hook@
CONST	SEGMENT
??_C@_0BI@BGFKABCN@corrupted?5function?5hook@ DB 'corrupted function hook'
	DB	00H						; `string'
CONST	ENDS
;	COMDAT ??_C@_0O@CANMLFDD@function?5hook@
CONST	SEGMENT
??_C@_0O@CANMLFDD@function?5hook@ DB 'function hook', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BD@FMPBNBIP@hook?5limit?5reached@
CONST	SEGMENT
??_C@_0BD@FMPBNBIP@hook?5limit?5reached@ DB 'hook limit reached', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BG@KLOCBMAN@incompatible?5function@
CONST	SEGMENT
??_C@_0BG@KLOCBMAN@incompatible?5function@ DB 'incompatible function', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BE@GADLECGJ@failed?5to?5run?5hooks@
CONST	SEGMENT
??_C@_0BE@GADLECGJ@failed?5to?5run?5hooks@ DB 'failed to run hooks', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_01EFFIKLCJ@n@
CONST	SEGMENT
??_C@_01EFFIKLCJ@n@ DB 'n', 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_0BI@PGPBJMFK@failed?5to?5prepare?5hooks@
CONST	SEGMENT
??_C@_0BI@PGPBJMFK@failed?5to?5prepare?5hooks@ DB 'failed to prepare hook'
	DB	's', 00H					; `string'
CONST	ENDS
;	COMDAT ??_C@_0BK@FGOEOOHP@an?5unknown?5error?5occurred@
CONST	SEGMENT
??_C@_0BK@FGOEOOHP@an?5unknown?5error?5occurred@ DB 'an unknown error occ'
	DB	'urred', 00H					; `string'
CONST	ENDS
;	COMDAT ??_C@_04HDOCAJNK@?$CFs?$CFs@
CONST	SEGMENT
??_C@_04HDOCAJNK@?$CFs?$CFs@ DB '%s%s', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_0BL@DGPOAGDD@failed?5to?5replace?5function@
CONST	SEGMENT
??_C@_0BL@DGPOAGDD@failed?5to?5replace?5function@ DB 'failed to replace f'
	DB	'unction', 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_08IEONNEJB@dsl_hook@
CONST	SEGMENT
??_C@_08IEONNEJB@dsl_hook@ DB 'dsl_hook', 00H		; `string'
CONST	ENDS
_DATA	SEGMENT
_g_libraries DD	0ae9da8H
	DD	0aeafa8H
	DD	0aea2c8H
	DD	0ae9aa8H
	DD	0ae96f8H
	DD	0ae9418H
	DD	0ae9530H
	DD	0ae9100H
	DD	0ae9958H
	DD	0aeb510H
	DD	0aeb200H
	DD	0aeb770H
	DD	0aeb6a8H
	DD	0aea580H
	DD	0ae9b20H
	DD	0ae9890H
	DD	0aea28cH
	DD	0ae9d40H
	DD	0aeb530H
	DD	0ae9990H
	DD	0aea310H
	DD	0aeaf38H
	DD	0aea3c8H
	DD	0aeb240H
	DD	0ae9f78H
	DD	0ae9918H
	DD	0ae94e0H
	DD	0aeb2b8H
	DD	0b9da18H
	DD	0bc6ed8H
	DD	0ae9a78H
	DD	0ae9518H
	DD	0bc6598H
	DD	0bc6700H
	DD	0bc6660H
	DD	0bc63d8H
	DD	0bc64f8H
	DD	0bc6298H
	DD	0bc6040H
	DD	0bc5f54H
	DD	0bc6af0H
	DD	0bc6c4cH
	DD	0bc6ff8H
	DD	0bc7170H
	DD	0bc5facH
	DD	0bc7068H
	DD	0bc68e8H
	DD	0bc6008H
	DD	0bc6b5cH
	DD	0bc6890H
	DD	0ae9b90H
	DD	0aeb674H
	DD	0ae9778H
	DD	0aea25cH
	DD	0ae9858H
	DD	0aeb748H
	DD	0ae9a28H
	DD	0aeb5c8H
_DATA	ENDS
; Function compile flags: /Ogtpy
;	COMDAT _dslopen_hook
_TEXT	SEGMENT
_lua$ = 8						; size = 4
_dslopen_hook PROC					; COMDAT
; File C:\Program Files (x86)\Steam\steamapps\common\Bully Scholarship Edition\_derpy_script_loader\src\client\library\lib_hook.c
; Line 419
	push	esi
	push	edi
; Line 378
	mov	edi, DWORD PTR _lua$[esp+4]
	push	OFFSET ??_C@_08IEONNEJB@dsl_hook@
	push	edi
	call	_lua_pushstring
; Line 379
	push	12					; 0000000cH
	push	edi
	call	_lua_newuserdata
	mov	esi, eax
	xorps	xmm0, xmm0
; Line 381
	push	edi
	movq	QWORD PTR [esi], xmm0
	mov	DWORD PTR [esi+8], 0
	call	_lua_newtable
; Line 382
	push	OFFSET ??_C@_04BDLIKKMN@__gc@
	push	edi
	call	_lua_pushstring
; Line 383
	push	0
	push	OFFSET _freeReplacements
	push	edi
	call	_lua_pushcclosure
; Line 384
	push	-3					; fffffffdH
	push	edi
	call	_lua_rawset
; Line 385
	push	-2					; fffffffeH
	push	edi
	call	_lua_setmetatable
; Line 386
	push	-10000					; ffffd8f0H
	push	edi
	call	_lua_rawset
	add	esp, 64					; 00000040H
; Line 420
	push	esi
	push	OFFSET _destroyedScript
	push	4
	push	1
	push	edi
	call	_getDslState
	add	esp, 8
	mov	eax, DWORD PTR [eax+20]
	push	eax
	call	_addScriptEventCallback
; Line 421
	push	OFFSET ??_C@_0BE@IDIDLGJD@GetBaseGameFunction@
	push	edi
	call	_lua_pushstring
	push	0
	push	OFFSET _GetBaseGameFunction
	push	edi
	call	_lua_pushcclosure
	push	-10001					; ffffd8efH
	push	edi
	call	_lua_settable
; Line 422
	push	OFFSET ??_C@_0N@EJLAAODM@HookFunction@
	push	edi
	call	_lua_pushstring
	push	0
	push	OFFSET _HookFunction
	push	edi
	call	_lua_pushcclosure
	add	esp, 64					; 00000040H
	push	-10001					; ffffd8efH
	push	edi
	call	_lua_settable
; Line 423
	push	OFFSET ??_C@_0BD@IMEMLEFD@RemoveFunctionHook@
	push	edi
	call	_lua_pushstring
	push	0
	push	OFFSET _RemoveFunctionHook
	push	edi
	call	_lua_pushcclosure
	push	-10001					; ffffd8efH
	push	edi
	call	_lua_settable
; Line 424
	push	OFFSET ??_C@_0BA@PAHFPGMI@ReplaceFunction@
	push	edi
	call	_lua_pushstring
	push	0
	push	OFFSET _ReplaceFunction
	push	edi
	call	_lua_pushcclosure
	push	-10001					; ffffd8efH
	push	edi
	call	_lua_settable
	add	esp, 64					; 00000040H
; Line 425
	xor	eax, eax
	pop	edi
	pop	esi
; Line 426
	ret	0
_dslopen_hook ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT _destroyedScript
_TEXT	SEGMENT
_index$1$ = -4						; size = 4
_lua$ = 8						; size = 4
_fr$ = 12						; size = 4
_s$ = 16						; size = 4
_destroyedScript PROC					; COMDAT
; File C:\Program Files (x86)\Steam\steamapps\common\Bully Scholarship Edition\_derpy_script_loader\src\client\library\lib_hook.c
; Line 389
	push	ecx
; Line 395
	mov	eax, DWORD PTR _fr$[esp]
	push	ebp
	mov	ebp, DWORD PTR [eax+4]
; Line 396
	test	ebp, ebp
	je	$LN70@destroyedS
	push	ebx
	push	esi
	push	edi
$LL2@destroyedS:
; Line 397
	mov	eax, DWORD PTR [eax]
	dec	ebp
	mov	DWORD PTR _index$1$[esp+20], ebp
	mov	ebp, DWORD PTR [eax+ebp*4]
	cmp	DWORD PTR [ebp], 0
	je	$LN12@destroyedS
; Line 398
	mov	ecx, DWORD PTR _s$[esp+16]
	cmp	DWORD PTR [ebp+8], ecx
	jne	SHORT $LN67@destroyedS
; Line 399
	mov	DWORD PTR [ebp+4], 0
$LN67@destroyedS:
; Line 400
	lea	edi, DWORD PTR [ebp+12]
	mov	ebx, 200				; 000000c8H
	mov	esi, edi
$LL6@destroyedS:
; Line 401
	cmp	DWORD PTR [esi+800], ecx
	jne	SHORT $LN4@destroyedS
	mov	eax, DWORD PTR [esi]
	cmp	eax, -2					; fffffffeH
	je	SHORT $LN4@destroyedS
; Line 402
	push	eax
	push	-10000					; ffffd8f0H
	push	DWORD PTR _lua$[esp+24]
	call	_luaL_unref
	mov	ecx, DWORD PTR _s$[esp+28]
	add	esp, 12					; 0000000cH
; Line 403
	mov	DWORD PTR [esi], -2			; fffffffeH
$LN4@destroyedS:
; Line 400
	add	esi, 4
	sub	ebx, 1
	jne	SHORT $LL6@destroyedS
; Line 157
	cmp	DWORD PTR [ebp+4], ebx
	jne	SHORT $LN10@destroyedS
; Line 159
	xor	eax, eax
	npad	4
$LL17@destroyedS:
; Line 160
	cmp	DWORD PTR [edi], -2			; fffffffeH
	jne	SHORT $LN10@destroyedS
; Line 159
	inc	eax
	add	edi, 4
	cmp	eax, 200				; 000000c8H
	jl	SHORT $LL17@destroyedS
; Line 113
	mov	edx, OFFSET _g_libraries+232
$LL22@destroyedS:
; Line 115
	mov	eax, DWORD PTR [edx-4]
	sub	edx, 4
	cmp	DWORD PTR [eax], 0
	je	SHORT $LN25@destroyedS
; Line 116
	mov	ecx, DWORD PTR [ebp]
$LL26@destroyedS:
	cmp	DWORD PTR [eax+4], ecx
	je	SHORT $LN45@destroyedS
; Line 115
	add	eax, 8
	cmp	DWORD PTR [eax], 0
	jne	SHORT $LL26@destroyedS
$LN25@destroyedS:
; Line 114
	cmp	edx, OFFSET _g_libraries
	jne	SHORT $LL22@destroyedS
; Line 118
	xor	eax, eax
$LN21@destroyedS:
; Line 406
	mov	esi, DWORD PTR _lua$[esp+16]
	push	eax
	push	esi
	call	_lua_pushstring
; Line 407
	push	0
	push	DWORD PTR [ebp]
	push	esi
	call	_lua_pushcclosure
; Line 408
	push	-10001					; ffffd8efH
	push	esi
	call	_lua_settable
	add	esp, 28					; 0000001cH
	jmp	SHORT $LN12@destroyedS
$LN45@destroyedS:
; Line 117
	mov	eax, DWORD PTR [eax]
	jmp	SHORT $LN21@destroyedS
$LN10@destroyedS:
; Line 409
	cmp	DWORD PTR [ebp+8], ecx
	jne	SHORT $LN12@destroyedS
; Line 113
	mov	edx, OFFSET _g_libraries+232
	npad	2
$LL30@destroyedS:
; Line 115
	mov	eax, DWORD PTR [edx-4]
	sub	edx, 4
	cmp	DWORD PTR [eax], 0
	je	SHORT $LN33@destroyedS
; Line 116
	mov	ecx, DWORD PTR [ebp]
	npad	2
$LL34@destroyedS:
	cmp	DWORD PTR [eax+4], ecx
	je	SHORT $LN46@destroyedS
; Line 115
	add	eax, 8
	cmp	DWORD PTR [eax], 0
	jne	SHORT $LL34@destroyedS
$LN33@destroyedS:
; Line 114
	cmp	edx, OFFSET _g_libraries
	jne	SHORT $LL30@destroyedS
; Line 118
	xor	eax, eax
$LN29@destroyedS:
; Line 410
	mov	ebx, DWORD PTR _lua$[esp+16]
	push	eax
	push	ebx
	call	_lua_pushstring
; Line 411
	push	ebp
	push	ebx
	call	_lua_pushlightuserdata
; Line 412
	push	ebx
	call	_lua_pushnil
; Line 413
	push	2
	push	OFFSET _replacedFunction
	push	ebx
	call	_lua_pushcclosure
; Line 414
	push	-10001					; ffffd8efH
	push	ebx
	call	_lua_settable
	add	esp, 40					; 00000028H
$LN12@destroyedS:
; Line 396
	mov	ebp, DWORD PTR _index$1$[esp+20]
	mov	eax, DWORD PTR _fr$[esp+16]
	test	ebp, ebp
	jne	$LL2@destroyedS
; Line 417
	pop	edi
	pop	esi
	pop	ebx
$LN70@destroyedS:
; Line 418
	xor	eax, eax
	pop	ebp
	pop	ecx
	ret	0
$LN46@destroyedS:
; Line 117
	mov	eax, DWORD PTR [eax]
	jmp	SHORT $LN29@destroyedS
_destroyedScript ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT _initReplacements
_TEXT	SEGMENT
_lua$ = 8						; size = 4
_initReplacements PROC					; COMDAT
; File C:\Program Files (x86)\Steam\steamapps\common\Bully Scholarship Edition\_derpy_script_loader\src\client\library\lib_hook.c
; Line 375
	push	esi
	push	edi
; Line 378
	mov	edi, DWORD PTR _lua$[esp+4]
	push	OFFSET ??_C@_08IEONNEJB@dsl_hook@
	push	edi
	call	_lua_pushstring
; Line 379
	push	12					; 0000000cH
	push	edi
	call	_lua_newuserdata
	mov	esi, eax
	xorps	xmm0, xmm0
; Line 381
	push	edi
	movq	QWORD PTR [esi], xmm0
	mov	DWORD PTR [esi+8], 0
	call	_lua_newtable
; Line 382
	push	OFFSET ??_C@_04BDLIKKMN@__gc@
	push	edi
	call	_lua_pushstring
; Line 383
	push	0
	push	OFFSET _freeReplacements
	push	edi
	call	_lua_pushcclosure
; Line 384
	push	-3					; fffffffdH
	push	edi
	call	_lua_rawset
; Line 385
	push	-2					; fffffffeH
	push	edi
	call	_lua_setmetatable
; Line 386
	push	-10000					; ffffd8f0H
	push	edi
	call	_lua_rawset
	add	esp, 64					; 00000040H
; Line 387
	mov	eax, esi
	pop	edi
	pop	esi
; Line 388
	ret	0
_initReplacements ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT _freeReplacements
_TEXT	SEGMENT
_lua$ = 8						; size = 4
_freeReplacements PROC					; COMDAT
; File C:\Program Files (x86)\Steam\steamapps\common\Bully Scholarship Edition\_derpy_script_loader\src\client\library\lib_hook.c
; Line 363
	push	esi
	push	edi
; Line 367
	push	1
	push	DWORD PTR _lua$[esp+8]
	call	_lua_touserdata
	mov	edi, eax
	add	esp, 8
	mov	esi, DWORD PTR [edi+4]
; Line 369
	test	esi, esi
	je	SHORT $LN3@freeReplac
	npad	7
$LL7@freeReplac:
; Line 370
	mov	ecx, DWORD PTR [edi]
	dec	esi
	push	DWORD PTR [ecx+esi*4]
	call	_free
	add	esp, 4
	test	esi, esi
	jne	SHORT $LL7@freeReplac
$LN3@freeReplac:
; Line 371
	push	DWORD PTR [edi]
	call	_free
	add	esp, 4
; Line 373
	xor	eax, eax
	pop	edi
	pop	esi
; Line 374
	ret	0
_freeReplacements ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT _ReplaceFunction
_TEXT	SEGMENT
_lua$ = 8						; size = 4
_ReplaceFunction PROC					; COMDAT
; File C:\Program Files (x86)\Steam\steamapps\common\Bully Scholarship Edition\_derpy_script_loader\src\client\library\lib_hook.c
; Line 325
	push	ebx
	push	ebp
	push	esi
; Line 330
	mov	esi, DWORD PTR _lua$[esp+8]
	push	edi
	push	4
	push	1
	push	esi
	call	_luaL_checktype
; Line 331
	push	esi
	call	_lua_gettop
	add	esp, 16					; 00000010H
	cmp	eax, 2
	jl	SHORT $LN2@ReplaceFun
	push	2
	push	esi
	call	_lua_type
	add	esp, 8
	test	eax, eax
	je	SHORT $LN2@ReplaceFun
; Line 332
	push	6
	push	2
	push	esi
	call	_luaL_checktype
	add	esp, 12					; 0000000cH
$LN2@ReplaceFun:
; Line 333
	push	esi
	call	_lua_gettop
	add	esp, 4
	cmp	eax, 3
	jl	SHORT $LN3@ReplaceFun
; Line 334
	push	1
	push	3
	push	esi
	call	_luaL_checktype
	add	esp, 12					; 0000000cH
$LN3@ReplaceFun:
; Line 335
	push	1
	push	esi
	call	_lua_tostring
	push	eax
	call	_getLuaFunction
	mov	ebx, eax
	add	esp, 12					; 0000000cH
; Line 336
	test	ebx, ebx
	jne	SHORT $LN4@ReplaceFun
; Line 337
	push	OFFSET ??_C@_0BG@KLOCBMAN@incompatible?5function@
	push	1
	push	esi
	call	_luaL_argerror
	add	esp, 12					; 0000000cH
$LN4@ReplaceFun:
; Line 338
	push	1
	push	esi
	call	_getDslState
; Line 339
	push	ebx
	push	esi
	mov	eax, DWORD PTR [eax+32]
	mov	ebp, DWORD PTR [eax+16]
	call	_getReplacement
	mov	edi, eax
	add	esp, 16					; 00000010H
; Line 340
	cmp	DWORD PTR [edi+4], 2
	jne	SHORT $LN7@ReplaceFun
	cmp	DWORD PTR [edi+8], ebp
	je	SHORT $LN7@ReplaceFun
; Line 358
	xor	eax, eax
; Line 359
	push	eax
	push	esi
	call	_lua_pushboolean
	add	esp, 8
	mov	eax, 1
	pop	edi
	pop	esi
	pop	ebp
	pop	ebx
; Line 360
	ret	0
$LN7@ReplaceFun:
; Line 342
	push	2
	push	esi
	mov	DWORD PTR [edi+8], ebp
	call	_lua_type
	add	esp, 8
	cmp	eax, 6
	jne	SHORT $LN8@ReplaceFun
; Line 343
	push	3
	push	esi
	call	_lua_toboolean
	add	esp, 8
	neg	eax
	sbb	eax, eax
	neg	eax
	inc	eax
	jmp	SHORT $LN9@ReplaceFun
$LN8@ReplaceFun:
; Line 345
	xor	eax, eax
$LN9@ReplaceFun:
; Line 157
	mov	DWORD PTR [edi+4], eax
	test	eax, eax
	jne	SHORT $LN25@ReplaceFun
; Line 159
	xor	ecx, ecx
	lea	eax, DWORD PTR [edi+12]
	npad	2
$LL17@ReplaceFun:
; Line 160
	cmp	DWORD PTR [eax], -2			; fffffffeH
	jne	SHORT $LN25@ReplaceFun
; Line 159
	inc	ecx
	add	eax, 4
	cmp	ecx, 200				; 000000c8H
	jl	SHORT $LL17@ReplaceFun
; Line 347
	mov	DWORD PTR [edi], 0
$LN25@ReplaceFun:
; Line 348
	push	1
	push	esi
	call	_lua_pushvalue
	add	esp, 8
; Line 349
	cmp	DWORD PTR [edi], 0
	je	SHORT $LN11@ReplaceFun
; Line 350
	push	edi
	push	esi
	call	_lua_pushlightuserdata
; Line 351
	push	2
	push	esi
	call	_lua_pushvalue
	add	esp, 16					; 00000010H
; Line 352
	mov	ebx, OFFSET _replacedFunction
	mov	eax, 2
; Line 353
	jmp	SHORT $LN12@ReplaceFun
$LN11@ReplaceFun:
; Line 354
	xor	eax, eax
$LN12@ReplaceFun:
; Line 355
	push	eax
	push	ebx
	push	esi
	call	_lua_pushcclosure
	push	-10001					; ffffd8efH
	push	esi
	call	_lua_settable
	add	esp, 20					; 00000014H
; Line 356
	mov	eax, 1
; Line 359
	push	eax
	push	esi
	call	_lua_pushboolean
	add	esp, 8
	mov	eax, 1
	pop	edi
	pop	esi
	pop	ebp
	pop	ebx
; Line 360
	ret	0
_ReplaceFunction ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT _RemoveFunctionHook
_TEXT	SEGMENT
_ptr$ = -4						; size = 4
_func$ = -4						; size = 4
_lua$ = 8						; size = 4
_RemoveFunctionHook PROC				; COMDAT
; File C:\Program Files (x86)\Steam\steamapps\common\Bully Scholarship Edition\_derpy_script_loader\src\client\library\lib_hook.c
; Line 304
	push	ecx
	push	ebx
	push	ebp
	push	esi
; Line 309
	mov	esi, DWORD PTR _lua$[esp+12]
	push	edi
	push	1
	push	esi
	call	_lua_touserdata
	mov	ebx, eax
	add	esp, 8
; Line 310
	test	ebx, ebx
	jne	SHORT $LN2@RemoveFunc
; Line 311
	push	OFFSET ??_C@_0O@CANMLFDD@function?5hook@
	push	1
	push	esi
	call	_luaL_typerror
	add	esp, 12					; 0000000cH
$LN2@RemoveFunc:
; Line 312
	cmp	DWORD PTR [ebx], 199			; 000000c7H
	ja	SHORT $LN24@RemoveFunc
	lea	eax, DWORD PTR [ebx+4]
	push	eax
	call	_getLuaFunction
	mov	ebp, eax
	add	esp, 4
	test	ebp, ebp
	je	SHORT $LN25@RemoveFunc
	push	ebp
	push	esi
	call	_getReplacement
	mov	edi, eax
	add	esp, 8
	test	edi, edi
	jne	SHORT $LN3@RemoveFunc
	jmp	SHORT $LN4@RemoveFunc
$LN24@RemoveFunc:
	mov	ebp, DWORD PTR _func$[esp+20]
$LN25@RemoveFunc:
; Line 313
	mov	edi, DWORD PTR _ptr$[esp+20]
$LN4@RemoveFunc:
	push	OFFSET ??_C@_0BI@BGFKABCN@corrupted?5function?5hook@
	push	esi
	call	_luaL_error
	add	esp, 8
$LN3@RemoveFunc:
; Line 314
	mov	eax, DWORD PTR [ebx]
	cmp	DWORD PTR [edi+eax*4+12], -2		; fffffffeH
	jne	SHORT $LN6@RemoveFunc
	push	1
	push	esi
	call	_getDslState
	mov	edx, DWORD PTR [ebx]
	add	esp, 8
	mov	ecx, DWORD PTR [eax+32]
	mov	eax, DWORD PTR [edi+edx*4+812]
	cmp	eax, DWORD PTR [ecx+16]
	je	SHORT $LN5@RemoveFunc
$LN6@RemoveFunc:
; Line 315
	push	OFFSET ??_C@_0BG@HOEJKLNH@invalid?5function?5hook@
	push	1
	push	esi
	call	_luaL_argerror
	mov	edx, DWORD PTR [ebx]
	add	esp, 12					; 0000000cH
$LN5@RemoveFunc:
; Line 316
	push	DWORD PTR [edi+edx*4+12]
	push	-10000					; ffffd8f0H
	push	esi
	call	_luaL_unref
; Line 317
	mov	eax, DWORD PTR [ebx]
	add	esp, 12					; 0000000cH
	mov	DWORD PTR [edi+eax*4+12], -2		; fffffffeH
; Line 157
	cmp	DWORD PTR [edi+4], 0
	jne	SHORT $LN23@RemoveFunc
; Line 159
	xor	ecx, ecx
	lea	eax, DWORD PTR [edi+12]
	npad	6
$LL12@RemoveFunc:
; Line 160
	cmp	DWORD PTR [eax], -2			; fffffffeH
	jne	SHORT $LN23@RemoveFunc
; Line 159
	inc	ecx
	add	eax, 4
	cmp	ecx, 200				; 000000c8H
	jl	SHORT $LL12@RemoveFunc
; Line 319
	lea	eax, DWORD PTR [ebx+4]
	push	eax
	push	esi
	call	_lua_pushstring
; Line 320
	push	0
	push	ebp
	push	esi
	call	_lua_pushcclosure
; Line 321
	push	-10001					; ffffd8efH
	push	esi
	call	_lua_settable
	add	esp, 28					; 0000001cH
$LN23@RemoveFunc:
; Line 324
	pop	edi
	pop	esi
	pop	ebp
	xor	eax, eax
	pop	ebx
	pop	ecx
	ret	0
_RemoveFunctionHook ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT _HookFunction
_TEXT	SEGMENT
$T1 = -4						; size = 4
_lua$ = 8						; size = 4
_HookFunction PROC					; COMDAT
; File C:\Program Files (x86)\Steam\steamapps\common\Bully Scholarship Edition\_derpy_script_loader\src\client\library\lib_hook.c
; Line 267
	push	ecx
	push	ebx
; Line 274
	mov	ebx, DWORD PTR _lua$[esp+4]
	push	esi
	push	edi
	push	4
	push	1
	push	ebx
	call	_luaL_checktype
; Line 275
	push	6
	push	2
	push	ebx
	call	_luaL_checktype
; Line 276
	push	2
	push	ebx
	call	_lua_settop
; Line 277
	push	1
	push	ebx
	call	_lua_tostring
	mov	edi, eax
; Line 278
	push	edi
	call	_getLuaFunction
	mov	esi, eax
	add	esp, 44					; 0000002cH
; Line 279
	test	esi, esi
	jne	SHORT $LN5@HookFuncti
; Line 280
	push	OFFSET ??_C@_0BG@KLOCBMAN@incompatible?5function@
	push	1
	push	ebx
	call	_luaL_argerror
	add	esp, 12					; 0000000cH
$LN5@HookFuncti:
; Line 281
	push	ebp
	push	esi
	push	ebx
	call	_getReplacement
	mov	ebp, eax
	add	esp, 8
; Line 282
	xor	esi, esi
	lea	ecx, DWORD PTR [ebp+16]
	npad	1
$LL4@HookFuncti:
; Line 283
	cmp	DWORD PTR [ecx-4], -2			; fffffffeH
	je	SHORT $LN22@HookFuncti
	cmp	DWORD PTR [ecx], -2			; fffffffeH
	je	SHORT $LN29@HookFuncti
	cmp	DWORD PTR [ecx+4], -2			; fffffffeH
	je	SHORT $LN30@HookFuncti
	cmp	DWORD PTR [ecx+8], -2			; fffffffeH
	je	SHORT $LN31@HookFuncti
	cmp	DWORD PTR [ecx+12], -2			; fffffffeH
	je	SHORT $LN32@HookFuncti
; Line 282
	add	esi, 5
	add	ecx, 20					; 00000014H
	cmp	esi, 200				; 000000c8H
	jl	SHORT $LL4@HookFuncti
	jmp	SHORT $LN22@HookFuncti
$LN32@HookFuncti:
; Line 283
	add	esi, 4
	jmp	SHORT $LN22@HookFuncti
$LN31@HookFuncti:
	add	esi, 3
	jmp	SHORT $LN22@HookFuncti
$LN30@HookFuncti:
	add	esi, 2
	jmp	SHORT $LN22@HookFuncti
$LN29@HookFuncti:
	inc	esi
$LN22@HookFuncti:
; Line 285
	cmp	esi, 200				; 000000c8H
	jne	SHORT $LN7@HookFuncti
; Line 286
	push	OFFSET ??_C@_0BD@FMPBNBIP@hook?5limit?5reached@
	push	ebx
	call	_luaL_error
	add	esp, 8
$LN7@HookFuncti:
; Line 287
	cmp	esi, DWORD PTR [ebp+1612]
	jl	SHORT $LN8@HookFuncti
; Line 288
	lea	eax, DWORD PTR [esi+1]
	mov	DWORD PTR [ebp+1612], eax
$LN8@HookFuncti:
; Line 157
	cmp	DWORD PTR [ebp+4], 0
	jne	SHORT $LN23@HookFuncti
; Line 159
	xor	ecx, ecx
	lea	eax, DWORD PTR [ebp+12]
	npad	1
$LL15@HookFuncti:
; Line 160
	cmp	DWORD PTR [eax], -2			; fffffffeH
	jne	SHORT $LN23@HookFuncti
; Line 159
	inc	ecx
	add	eax, 4
	cmp	ecx, 200				; 000000c8H
	jl	SHORT $LL15@HookFuncti
; Line 162
	mov	DWORD PTR $T1[esp+20], 0
	jmp	SHORT $LN12@HookFuncti
$LN23@HookFuncti:
; Line 290
	mov	DWORD PTR $T1[esp+20], 1
$LN12@HookFuncti:
	push	1
	push	ebx
	call	_getDslState
; Line 291
	push	-10000					; ffffd8f0H
	push	ebx
	mov	eax, DWORD PTR [eax+32]
	mov	eax, DWORD PTR [eax+16]
	mov	DWORD PTR [ebp+esi*4+812], eax
	call	_luaL_ref
	add	esp, 16					; 00000010H
	mov	DWORD PTR [ebp+esi*4+12], eax
	cmp	DWORD PTR $T1[esp+20], 0
; Line 292
	jne	SHORT $LN9@HookFuncti
; Line 293
	push	1
	push	ebx
	call	_lua_pushvalue
; Line 294
	push	ebp
	push	ebx
	call	_lua_pushlightuserdata
; Line 295
	push	ebx
	call	_lua_pushnil
; Line 296
	push	2
	push	OFFSET _replacedFunction
	push	ebx
	call	_lua_pushcclosure
; Line 297
	push	-10001					; ffffd8efH
	push	ebx
	call	_lua_settable
	add	esp, 40					; 00000028H
$LN9@HookFuncti:
; Line 299
	mov	ecx, edi
	pop	ebp
	lea	edx, DWORD PTR [ecx+1]
$LL36@HookFuncti:
	mov	al, BYTE PTR [ecx]
	inc	ecx
	test	al, al
	jne	SHORT $LL36@HookFuncti
	sub	ecx, edx
	lea	eax, DWORD PTR [ecx+5]
	push	eax
	push	ebx
	call	_lua_newuserdata
	add	esp, 8
; Line 300
	mov	DWORD PTR [eax], 1
; Line 301
	sub	eax, edi
	lea	ecx, DWORD PTR [eax+4]
	npad	8
$LL11@HookFuncti:
	mov	al, BYTE PTR [edi]
	lea	edi, DWORD PTR [edi+1]
	mov	BYTE PTR [ecx+edi-1], al
	test	al, al
	jne	SHORT $LL11@HookFuncti
; Line 302
	pop	edi
	pop	esi
	mov	eax, 1
	pop	ebx
; Line 303
	pop	ecx
	ret	0
_HookFunction ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT _GetBaseGameFunction
_TEXT	SEGMENT
_lua$ = 8						; size = 4
_GetBaseGameFunction PROC				; COMDAT
; File C:\Program Files (x86)\Steam\steamapps\common\Bully Scholarship Edition\_derpy_script_loader\src\client\library\lib_hook.c
; Line 257
	push	esi
; Line 260
	mov	esi, DWORD PTR _lua$[esp]
	push	4
	push	1
	push	esi
	call	_luaL_checktype
; Line 261
	push	1
	push	esi
	call	_lua_tostring
	push	eax
	call	_getLuaFunction
	add	esp, 24					; 00000018H
; Line 262
	test	eax, eax
	jne	SHORT $LN2@GetBaseGam
	pop	esi
; Line 266
	ret	0
$LN2@GetBaseGam:
; Line 264
	push	0
	push	eax
	push	esi
	call	_lua_pushcclosure
	add	esp, 12					; 0000000cH
; Line 265
	mov	eax, 1
	pop	esi
; Line 266
	ret	0
_GetBaseGameFunction ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT _replacedFunction
_TEXT	SEGMENT
_argbase$1$ = -12					; size = 4
_ptr$1$ = -8						; size = 4
_stack$1$ = -4						; size = 4
_lua$ = 8						; size = 4
_replacedFunction PROC					; COMDAT
; File C:\Program Files (x86)\Steam\steamapps\common\Bully Scholarship Edition\_derpy_script_loader\src\client\library\lib_hook.c
; Line 177
	sub	esp, 12					; 0000000cH
	push	ebx
	push	ebp
	push	esi
; Line 187
	mov	esi, DWORD PTR _lua$[esp+20]
	push	edi
	push	-10002					; ffffd8eeH
	push	esi
	call	_lua_touserdata
	mov	ebx, eax
; Line 188
	push	-10003					; ffffd8edH
	push	esi
	mov	DWORD PTR _ptr$1$[esp+44], ebx
	call	_lua_pushvalue
	add	esp, 16					; 00000010H
; Line 189
	cmp	DWORD PTR [ebx], 0
	je	SHORT $LN33@replacedFu
	push	-1
	push	esi
	call	_lua_type
	add	esp, 8
	cmp	eax, 6
	jne	SHORT $LN33@replacedFu
; Line 190
	push	1
	push	esi
	call	_lua_insert
; Line 194
	mov	edi, 3
	lea	ebp, DWORD PTR [edi-1]
; Line 195
	jmp	SHORT $LN36@replacedFu
$LN33@replacedFu:
; Line 196
	push	-2					; fffffffeH
	push	esi
	call	_lua_settop
; Line 200
	mov	edi, 2
	lea	ebp, DWORD PTR [edi-1]
$LN36@replacedFu:
; Line 202
	mov	eax, DWORD PTR [ebx]
	add	esp, 8
	mov	DWORD PTR _argbase$1$[esp+28], edi
	push	0
	push	eax
	push	esi
	call	_lua_pushcclosure
	push	ebp
	push	esi
	call	_lua_insert
	push	esi
	call	_lua_gettop
	add	esp, 24					; 00000018H
	mov	ebp, eax
	cmp	DWORD PTR [ebx], 0
	je	$LN12@replacedFu
	cmp	DWORD PTR [ebx+1612], 0
	je	$LN12@replacedFu
; Line 203
	lea	ecx, DWORD PTR [ebp+20]
	push	ecx
	push	esi
	call	_lua_checkstack
	add	esp, 8
	test	eax, eax
	jne	SHORT $LN13@replacedFu
; Line 204
	push	OFFSET ??_C@_0BI@PGPBJMFK@failed?5to?5prepare?5hooks@
	push	esi
	call	_luaL_error
	add	esp, 8
$LN13@replacedFu:
; Line 205
	push	esi
	call	_lua_newtable
	add	esp, 4
; Line 207
	cmp	DWORD PTR _argbase$1$[esp+28], ebp
	jg	SHORT $LN3@replacedFu
; Line 205
	xor	ebx, ebx
	npad	5
$LL2@replacedFu:
; Line 208
	push	edi
	push	esi
	call	_lua_pushvalue
	inc	ebx
	inc	edi
; Line 209
	push	ebx
	push	-2					; fffffffeH
	push	esi
	call	_lua_rawseti
	add	esp, 20					; 00000014H
	cmp	edi, ebp
	jle	SHORT $LL2@replacedFu
	mov	ebx, DWORD PTR _ptr$1$[esp+28]
$LN3@replacedFu:
; Line 211
	push	OFFSET ??_C@_01EFFIKLCJ@n@
	push	esi
	call	_lua_pushstring
; Line 212
	mov	eax, ebp
	add	esp, 4
	sub	eax, DWORD PTR _argbase$1$[esp+32]
	inc	eax
	movd	xmm0, eax
	cvtdq2ps xmm0, xmm0
	movss	DWORD PTR [esp], xmm0
	push	esi
	call	_lua_pushnumber
; Line 213
	push	-3					; fffffffdH
	push	esi
	call	_lua_rawset
; Line 214
	push	1
	push	esi
	call	_lua_insert
	add	esp, 24					; 00000018H
$LN12@replacedFu:
; Line 220
	push	0
	push	-1
	lea	eax, DWORD PTR [ebp-1]
	push	eax
	push	esi
	call	_lua_pcall
	add	esp, 16					; 00000010H
	test	eax, eax
	je	SHORT $LN14@replacedFu
; Line 221
	push	esi
	call	_printFailure
	add	esp, 4
$LN14@replacedFu:
; Line 225
	push	esi
	call	_lua_gettop
	add	esp, 4
	mov	ebp, eax
; Line 226
	cmp	DWORD PTR [ebx], 0
	je	$LN34@replacedFu
	cmp	DWORD PTR [ebx+1612], 0
	je	$LN34@replacedFu
; Line 227
	lea	ecx, DWORD PTR [ebp+20]
	push	ecx
	push	esi
	call	_lua_checkstack
	add	esp, 8
	test	eax, eax
	jne	SHORT $LN16@replacedFu
; Line 228
	push	OFFSET ??_C@_0BE@GADLECGJ@failed?5to?5run?5hooks@
	push	esi
	call	_luaL_error
	add	esp, 8
$LN16@replacedFu:
; Line 229
	push	esi
	call	_lua_newtable
	mov	edi, 2
	add	esp, 4
; Line 230
	cmp	ebp, edi
	jl	SHORT $LN5@replacedFu
$LL6@replacedFu:
; Line 231
	push	edi
	push	esi
	call	_lua_pushvalue
; Line 232
	lea	eax, DWORD PTR [edi-1]
	push	eax
	push	-2					; fffffffeH
	push	esi
	call	_lua_rawseti
	inc	edi
	add	esp, 20					; 00000014H
	cmp	edi, ebp
	jle	SHORT $LL6@replacedFu
$LN5@replacedFu:
; Line 235
	push	OFFSET ??_C@_01EFFIKLCJ@n@
	dec	ebp
	push	esi
	mov	DWORD PTR _stack$1$[esp+36], ebp
	call	_lua_pushstring
	movd	xmm0, ebp
; Line 236
	add	esp, 4
	cvtdq2ps xmm0, xmm0
	movss	DWORD PTR [esp], xmm0
	push	esi
	call	_lua_pushnumber
; Line 237
	push	-3					; fffffffdH
	push	esi
	call	_lua_rawset
; Line 238
	mov	eax, DWORD PTR _ptr$1$[esp+44]
	xor	ebx, ebx
	add	esp, 16					; 00000010H
	cmp	DWORD PTR [eax+1612], ebx
	jle	SHORT $LN8@replacedFu
; Line 234
	lea	edi, DWORD PTR [eax+12]
	mov	ebp, eax
$LL9@replacedFu:
; Line 239
	mov	eax, DWORD PTR [edi]
	cmp	eax, -2					; fffffffeH
	je	SHORT $LN7@replacedFu
; Line 240
	push	eax
	push	-10000					; ffffd8f0H
	push	esi
	call	_lua_rawgeti
; Line 241
	push	1
	push	esi
	call	_lua_pushvalue
; Line 242
	push	-3					; fffffffdH
	push	esi
	call	_lua_pushvalue
; Line 243
	xor	eax, eax
	cmp	DWORD PTR _argbase$1$[esp+56], 3
	sete	al
	push	eax
	push	esi
	call	_lua_pushboolean
; Line 247
	push	0
	push	0
	push	3
	push	esi
	call	_lua_pcall
	add	esp, 52					; 00000034H
	test	eax, eax
	je	SHORT $LN7@replacedFu
; Line 248
	push	esi
	call	_printFailure
	add	esp, 4
$LN7@replacedFu:
; Line 238
	inc	ebx
	add	edi, 4
	cmp	ebx, DWORD PTR [ebp+1612]
	jl	SHORT $LL9@replacedFu
	mov	ebp, DWORD PTR _stack$1$[esp+28]
$LN8@replacedFu:
; Line 253
	push	-2					; fffffffeH
	push	esi
	call	_lua_settop
	add	esp, 8
$LN34@replacedFu:
; Line 256
	pop	edi
	pop	esi
	mov	eax, ebp
	pop	ebp
	pop	ebx
	add	esp, 12					; 0000000cH
	ret	0
_replacedFunction ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT _printFailure
_TEXT	SEGMENT
_lua$ = 8						; size = 4
_printFailure PROC					; COMDAT
; File C:\Program Files (x86)\Steam\steamapps\common\Bully Scholarship Edition\_derpy_script_loader\src\client\library\lib_hook.c
; Line 164
	push	esi
; Line 167
	mov	esi, DWORD PTR _lua$[esp]
	push	edi
	push	0
	push	esi
	call	_getDslState
	mov	edi, eax
	add	esp, 8
	test	edi, edi
	je	SHORT $LN4@printFailu
; Line 168
	push	-1
	push	esi
	call	_lua_isstring
	add	esp, 8
	test	eax, eax
	je	SHORT $LN3@printFailu
; Line 169
	push	-1
	push	esi
	call	_lua_tostring
	add	esp, 8
	push	eax
	jmp	SHORT $LN6@printFailu
$LN3@printFailu:
; Line 171
	push	OFFSET ??_C@_0BK@FGOEOOHP@an?5unknown?5error?5occurred@
$LN6@printFailu:
; Line 173
	push	1
	push	edi
	call	_getDslPrintPrefix
	add	esp, 8
	push	eax
	push	OFFSET ??_C@_04HDOCAJNK@?$CFs?$CFs@
	push	1
	push	DWORD PTR [edi+24]
	call	_printConsoleFormatted
	add	esp, 20					; 00000014H
$LN4@printFailu:
	push	-2					; fffffffeH
	push	esi
	call	_lua_settop
	add	esp, 8
	pop	edi
	pop	esi
; Line 174
	ret	0
_printFailure ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT _isReplacementNeeded
_TEXT	SEGMENT
_ptr$ = 8						; size = 4
_isReplacementNeeded PROC				; COMDAT
; File C:\Program Files (x86)\Steam\steamapps\common\Bully Scholarship Edition\_derpy_script_loader\src\client\library\lib_hook.c
; Line 157
	mov	eax, DWORD PTR _ptr$[esp-4]
	cmp	DWORD PTR [eax+4], 0
	jne	SHORT $LN9@isReplacem
; Line 159
	xor	ecx, ecx
	add	eax, 12					; 0000000cH
	npad	1
$LL4@isReplacem:
; Line 160
	cmp	DWORD PTR [eax], -2			; fffffffeH
	jne	SHORT $LN9@isReplacem
; Line 159
	inc	ecx
	add	eax, 4
	cmp	ecx, 200				; 000000c8H
	jl	SHORT $LL4@isReplacem
; Line 162
	xor	eax, eax
; Line 163
	ret	0
$LN9@isReplacem:
; Line 161
	mov	eax, 1
; Line 163
	ret	0
_isReplacementNeeded ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT _getReplacement
_TEXT	SEGMENT
_ptr$2$ = -4						; size = 4
_lua$ = 8						; size = 4
_func$ = 12						; size = 4
_getReplacement PROC					; COMDAT
; File C:\Program Files (x86)\Steam\steamapps\common\Bully Scholarship Edition\_derpy_script_loader\src\client\library\lib_hook.c
; Line 120
	push	ecx
	push	ebx
	push	ebp
	push	esi
	push	edi
; Line 126
	mov	edi, DWORD PTR _lua$[esp+16]
	push	OFFSET ??_C@_08IEONNEJB@dsl_hook@
	push	edi
	call	_lua_pushstring
; Line 127
	push	-10000					; ffffd8f0H
	push	edi
	call	_lua_rawget
; Line 128
	push	-1
	push	edi
	call	_lua_touserdata
; Line 129
	push	-2					; fffffffeH
	push	edi
	mov	ebx, eax
	call	_lua_settop
; Line 130
	mov	ecx, DWORD PTR [ebx+4]
	add	esp, 32					; 00000020H
; Line 131
	mov	ebp, DWORD PTR _func$[esp+16]
	test	ecx, ecx
	je	SHORT $LN3@getReplace
; Line 132
	mov	eax, DWORD PTR [ebx]
	lea	edx, DWORD PTR [eax+ecx*4]
$LL2@getReplace:
	mov	esi, DWORD PTR [edx-4]
	lea	edx, DWORD PTR [edx-4]
	dec	ecx
; Line 133
	mov	eax, DWORD PTR [esi]
	test	eax, eax
	je	$LN15@getReplace
	cmp	eax, ebp
	je	$LN15@getReplace
; Line 131
	test	ecx, ecx
	jne	SHORT $LL2@getReplace
; Line 133
	mov	ecx, DWORD PTR [ebx+4]
$LN3@getReplace:
; Line 136
	mov	eax, DWORD PTR [ebx+8]
	cmp	ecx, eax
	jne	SHORT $LN22@getReplace
; Line 137
	lea	esi, DWORD PTR [eax+32]
; Line 138
	lea	eax, DWORD PTR [esi*4]
	push	eax
	push	DWORD PTR [ebx]
	call	_realloc
	add	esp, 8
	mov	DWORD PTR _ptr$2$[esp+20], eax
; Line 139
	test	eax, eax
	jne	SHORT $LN10@getReplace
; Line 140
	push	OFFSET ??_C@_0BL@DGPOAGDD@failed?5to?5replace?5function@
	push	edi
	call	_luaL_error
	mov	eax, DWORD PTR _ptr$2$[esp+28]
	add	esp, 8
$LN10@getReplace:
; Line 141
	mov	DWORD PTR [ebx], eax
; Line 142
	mov	DWORD PTR [ebx+8], esi
$LN22@getReplace:
; Line 144
	push	1616					; 00000650H
	call	_malloc
	mov	esi, eax
	add	esp, 4
; Line 145
	test	esi, esi
	jne	SHORT $LN11@getReplace
; Line 146
	push	OFFSET ??_C@_0BL@DGPOAGDD@failed?5to?5replace?5function@
	push	edi
	call	_luaL_error
	add	esp, 8
$LN11@getReplace:
; Line 147
	mov	DWORD PTR [esi], ebp
	lea	edi, DWORD PTR [esi+12]
; Line 148
	mov	DWORD PTR [esi+4], 0
	mov	eax, -2					; fffffffeH
	mov	ecx, 200				; 000000c8H
	rep stosd
; Line 151
	mov	DWORD PTR [esi+1612], 0
; Line 152
	mov	ecx, DWORD PTR [ebx+4]
	mov	eax, DWORD PTR [ebx]
	mov	DWORD PTR [eax+ecx*4], esi
	inc	DWORD PTR [ebx+4]
$LN15@getReplace:
; Line 153
	pop	edi
	mov	eax, esi
	pop	esi
	pop	ebp
	pop	ebx
	pop	ecx
	ret	0
_getReplacement ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT _getLuaFunctionName
_TEXT	SEGMENT
_func$ = 8						; size = 4
_getLuaFunctionName PROC				; COMDAT
; File C:\Program Files (x86)\Steam\steamapps\common\Bully Scholarship Edition\_derpy_script_loader\src\client\library\lib_hook.c
; Line 113
	mov	edx, DWORD PTR _func$[esp-4]
	mov	ecx, OFFSET _g_libraries+232
	npad	7
$LL2@getLuaFunc:
; Line 115
	mov	eax, DWORD PTR [ecx-4]
	sub	ecx, 4
	cmp	DWORD PTR [eax], 0
	je	SHORT $LN5@getLuaFunc
	npad	5
$LL6@getLuaFunc:
; Line 116
	cmp	DWORD PTR [eax+4], edx
	je	SHORT $LN11@getLuaFunc
; Line 115
	add	eax, 8
	cmp	DWORD PTR [eax], 0
	jne	SHORT $LL6@getLuaFunc
$LN5@getLuaFunc:
; Line 114
	cmp	ecx, OFFSET _g_libraries
	jne	SHORT $LL2@getLuaFunc
; Line 118
	xor	eax, eax
; Line 119
	ret	0
$LN11@getLuaFunc:
; Line 117
	mov	eax, DWORD PTR [eax]
; Line 119
	ret	0
_getLuaFunctionName ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT _getLuaFunction
_TEXT	SEGMENT
_name$ = 8						; size = 4
_getLuaFunction PROC					; COMDAT
; File C:\Program Files (x86)\Steam\steamapps\common\Bully Scholarship Edition\_derpy_script_loader\src\client\library\lib_hook.c
; Line 98
	push	ebx
; Line 102
	mov	ebx, DWORD PTR _name$[esp]
	push	esi
	push	edi
	mov	edi, OFFSET _g_libraries+232
	npad	4
$LL2@getLuaFunc:
; Line 104
	mov	esi, DWORD PTR [edi-4]
	sub	edi, 4
	mov	eax, DWORD PTR [esi]
	test	eax, eax
	je	SHORT $LN5@getLuaFunc
	npad	4
$LL6@getLuaFunc:
; Line 105
	mov	ecx, ebx
$LL18@getLuaFunc:
	mov	dl, BYTE PTR [eax]
	cmp	dl, BYTE PTR [ecx]
	jne	SHORT $LN19@getLuaFunc
	test	dl, dl
	je	SHORT $LN20@getLuaFunc
	mov	dl, BYTE PTR [eax+1]
	cmp	dl, BYTE PTR [ecx+1]
	jne	SHORT $LN19@getLuaFunc
	add	eax, 2
	add	ecx, 2
	test	dl, dl
	jne	SHORT $LL18@getLuaFunc
$LN20@getLuaFunc:
	xor	eax, eax
	jmp	SHORT $LN21@getLuaFunc
$LN19@getLuaFunc:
	sbb	eax, eax
	or	eax, 1
$LN21@getLuaFunc:
	test	eax, eax
	je	SHORT $LN11@getLuaFunc
; Line 104
	mov	eax, DWORD PTR [esi+8]
	add	esi, 8
	test	eax, eax
	jne	SHORT $LL6@getLuaFunc
$LN5@getLuaFunc:
; Line 103
	cmp	edi, OFFSET _g_libraries
	jne	SHORT $LL2@getLuaFunc
; Line 108
	pop	edi
	pop	esi
	xor	eax, eax
	pop	ebx
	ret	0
$LN11@getLuaFunc:
; Line 106
	mov	eax, DWORD PTR [esi+4]
	pop	edi
; Line 108
	pop	esi
	pop	ebx
	ret	0
_getLuaFunction ENDP
_TEXT	ENDS
END
