; Listing generated by Microsoft (R) Optimizing Compiler Version 19.23.28107.0 

	TITLE	C:\Program Files (x86)\Steam\steamapps\common\Bully Scholarship Edition\_derpy_script_loader\src\client\library\lib_vehicle.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_dslopen_vehicle
; Function compile flags: /Ogtpy
;	COMDAT _dslopen_vehicle
_TEXT	SEGMENT
_lua$ = 8						; size = 4
_dslopen_vehicle PROC					; COMDAT
; File C:\Program Files (x86)\Steam\steamapps\common\Bully Scholarship Edition\_derpy_script_loader\src\client\library\lib_vehicle.c
; Line 30
	xor	eax, eax
; Line 31
	ret	0
_dslopen_vehicle ENDP
_TEXT	ENDS
END
